### ISSUE TITLE
下载贴纸包报错

### ISSUE THREAD

**Issue by 502milk** [grasspow/TelegramStickersDownloadBot#1]
贴纸包地址https://t.me/addstickers/thecutestrabbit

报错日志
G:\桌面\sticker\TelegramStickersDownloadBot>npm install && npm start

up to date, audited 176 packages in 1s

52 packages are looking for funding
  run `npm fund` for details

5 moderate severity vulnerabilities

Some issues need review, and may require choosing
a different dependency.

Run `npm audit` for details.

> stickersdownloadbot@1.0.0 start
> node bot.js

压缩失败: ArchiverError: diretory dirpath argument must be a non-empty string value
    at Archiver.directory (G:\桌面\sticker\TelegramStickersDownloadBot\node_modules\archiver\lib\core.js:612:24)
    at G:\桌面\sticker\TelegramStickersDownloadBot\bot.js:41:17
    at new Promise (<anonymous>)
    at compressFolder (G:\桌面\sticker\TelegramStickersDownloadBot\bot.js:33:12)
    at G:\桌面\sticker\TelegramStickersDownloadBot\bot.js:55:23
    at stickersHandler (G:\桌面\sticker\TelegramStickersDownloadBot\bot.js:60:11)
    at Object.callback (G:\桌面\sticker\TelegramStickersDownloadBot\bot.js:67:5)
    at G:\桌面\sticker\TelegramStickersDownloadBot\node_modules\node-telegram-bot-api\src\telegram.js:696:15
    at Array.some (<anonymous>)
    at TelegramBot.processUpdate (G:\桌面\sticker\TelegramStickersDownloadBot\node_modules\node-telegram-bot-api\src\telegram.js:687:35)
    at G:\桌面\sticker\TelegramStickersDownloadBot\node_modules\node-telegram-bot-api\src\telegramPolling.js:110:22
    at Array.forEach (<anonymous>)
    at G:\桌面\sticker\TelegramStickersDownloadBot\node_modules\node-telegram-bot-api\src\telegramPolling.js:106:17
    at tryCatcher (G:\桌面\sticker\TelegramStickersDownloadBot\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (G:\桌面\sticker\TelegramStickersDownloadBot\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (G:\桌面\sticker\TelegramStickersDownloadBot\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (G:\桌面\sticker\TelegramStickersDownloadBot\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (G:\桌面\sticker\TelegramStickersDownloadBot\node_modules\bluebird\js\release\promise.js:729:18)
    at _drainQueueStep (G:\桌面\sticker\TelegramStickersDownloadBot\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (G:\桌面\sticker\TelegramStickersDownloadBot\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (G:\桌面\sticker\TelegramStickersDownloadBot\node_modules\bluebird\js\release\async.js:102:5)
    at Async.drainQueues (G:\桌面\sticker\TelegramStickersDownloadBot\node_modules\bluebird\js\release\async.js:15:14) {
  code: 'DIRECTORYDIRPATHREQUIRED',
  data: undefined
}
node:fs:1396
  handleErrorFromBinding(ctx);
  ^

Error: ENOENT: no such file or directory, mkdir 'undefined/thecutestrabbit/'
    at Object.mkdirSync (node:fs:1396:3)
    at downloadStickers (G:\桌面\sticker\TelegramStickersDownloadBot\bot.js:13:16) {
  errno: -4058,
  syscall: 'mkdir',
  code: 'ENOENT',
  path: 'undefined/thecutestrabbit/'
}

Node.js v18.16.1

**Comment by grasspow** [comment]
不好意思，刚看到🤣。
在修了在修了。。。

**Comment by grasspow** [comment]
现在很好奇当时的自己是怎么写的（

**Comment by 502milk** [comment]
> 不好意思，刚看到🤣。
> 在修了在修了。。。

光速修好
